# Generated by Django 5.0.4 on 2024-05-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='Maestri.group', help_text='Propósito principal da página', max_length=50, verbose_name='Propósito principal da página')),
                ('description', models.TextField(default='Página de apresentação da Maestri.group', help_text='Descrição da página', verbose_name='Descrição da página')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Página de destino',
                'verbose_name_plural': 'Páginas de destino',
            },
        ),
        migrations.CreateModel(
            name='HtmlBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(default='<div></div>', help_text='HTML do modelo', verbose_name='HTML do modelo')),
                ('theme_color', models.CharField(default='#000000', help_text='Cor do tema', max_length=7, verbose_name='Cor do tema')),
                ('title', models.CharField(default='Maestri.group', help_text='Título da página', max_length=50, verbose_name='Título da página')),
                ('description', models.TextField(default='Página de apresentação da Maestri.group', help_text='Descrição da página', verbose_name='Descrição da página')),
                ('keywords', models.TextField(default='Maestri, group, maestri.group', help_text='Palavras-chave da página', verbose_name='Palavras-chave da página')),
                ('author', models.CharField(default='Maestri.group', help_text='Autor da página', max_length=50, verbose_name='Autor da página')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Modelo base do HTML',
                'verbose_name_plural': 'Modelos base do HTML',
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='alphapage', help_text='Nome do modelo', max_length=50, verbose_name='Nome do modelo')),
                ('description', models.TextField(default='Modelo protótipo, de páginas dinâmicas atualizadas por AI', help_text='Descrição do modelo', verbose_name='Descrição do modelo')),
                ('html_base', models.TextField(default='alpha_base.html', help_text='HTML base do modelo', verbose_name='HTML base do modelo')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Modelo base de página',
                'verbose_name_plural': 'Modelos base de páginas',
            },
        ),
        migrations.CreateModel(
            name='FixedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(default='favicon.png', help_text='Ícone da página', upload_to='favicon/', verbose_name='Ícone da página')),
                ('domain', models.CharField(default='maestri.group', help_text='Domínio da página', max_length=50, verbose_name='Domínio da página')),
                ('facebook', models.URLField(default='https://www.facebook.com/maestri.group', help_text='Facebook da página', verbose_name='Facebook da página')),
                ('instagram', models.URLField(default='https://www.instagram.com/maestri.group', help_text='Instagram da página', verbose_name='Instagram da página')),
                ('whatsapp', models.URLField(default='https://api.whatsapp.com/send?phone=558003333099', help_text='Whatsapp da página', verbose_name='Whatsapp da página')),
                ('destination', models.ForeignKey(help_text='Página de destino da informação fixa', on_delete=django.db.models.deletion.CASCADE, to='aipag.destination', verbose_name='Página de destino da informação fixa')),
            ],
            options={
                'verbose_name': 'Informação fixa da página',
                'verbose_name_plural': 'Informações fixas das páginas',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='logo.png', help_text='Logotipo da página', upload_to='logo/', verbose_name='Logotipo da página')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Data de criação')),
                ('destination', models.ForeignKey(help_text='Página de destino do logotipo', on_delete=django.db.models.deletion.CASCADE, to='aipag.destination', verbose_name='Página de destino do logotipo')),
            ],
            options={
                'verbose_name': 'Logotipo da página',
                'verbose_name_plural': 'Logotipos da página',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='template',
            field=models.ForeignKey(help_text='Modelo base da página', on_delete=django.db.models.deletion.CASCADE, to='aipag.pagetemplate', verbose_name='Modelo base da página'),
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(default='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js', help_text='Script do modelo', verbose_name='Script')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Data de criação')),
                ('html_base', models.ForeignKey(help_text='HTML base para o script', on_delete=django.db.models.deletion.CASCADE, to='aipag.htmlbase', verbose_name='HTML base para o script')),
            ],
            options={
                'verbose_name': 'Script da página',
                'verbose_name_plural': 'Scripts das páginas',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(default='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css', help_text='Caminho do arquivo CSS', verbose_name='Caminho do CSS')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Data de criação')),
                ('html_base', models.ForeignKey(help_text='Modelo base do estilo', on_delete=django.db.models.deletion.CASCADE, to='aipag.htmlbase', verbose_name='Modelo base do estilo')),
            ],
            options={
                'verbose_name': 'Estilo CSS',
                'verbose_name_plural': 'Estilos CSS',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0.0.1', help_text='Versão', max_length=50, verbose_name='Versão')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Data de criação', verbose_name='Data de criação')),
                ('destination', models.ForeignKey(help_text='Página de destino da versão', on_delete=django.db.models.deletion.CASCADE, to='aipag.destination', verbose_name='Página de destino da versão')),
                ('template', models.ForeignKey(help_text='Modelo base da versão', on_delete=django.db.models.deletion.CASCADE, to='aipag.pagetemplate', verbose_name='Modelo base da versão')),
            ],
            options={
                'verbose_name': 'Versão da página',
                'verbose_name_plural': 'Versões das páginas',
            },
        ),
        migrations.AddField(
            model_name='htmlbase',
            name='version',
            field=models.ForeignKey(help_text='Versão do HTML', on_delete=django.db.models.deletion.CASCADE, to='aipag.version', verbose_name='Versão do HTML'),
        ),
    ]
