# Generated by Django 5.0.4 on 2024-05-01 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_globalsettings_and_more'),
        ('courses', '0002_alter_course_area_alter_course_duration_and_more'),
        ('profiles', '0002_estado_regiao_alter_graduation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('PRE_ENROLLED', 'Aluno Pré-Matriculado'), ('ENROLLED', 'Aluno Matriculado'), ('RE_ENROLLED', 'Veterano'), ('CANCELLED', 'Cancelado'), ('SUSPENDED', 'Trancado'), ('TRANSFERRED', 'Transferido'), ('ALUMNI', 'Ex-Aluno'), ('BLOCKED', 'Aluno com Pendências Financeiras'), ('OTHER', 'Outro')], help_text='Status do cliente.', max_length=12, verbose_name='Status do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='campaigns.classifications')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('user_speech_id', models.ForeignKey(help_text='Tutor responsável pelo aluno.', on_delete=django.db.models.deletion.CASCADE, related_name='tutor_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Tutor Responsável')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.landingpage')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.clients')),
            ],
        ),
    ]
