# Generated by Django 4.2.13 on 2024-05-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_alter_profile_age'),
        ('courses', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=2)),
                ('commission', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('PRE_ENROLLED', 'Aluno Pré-Matriculado'), ('ENROLLED', 'Aluno Matriculado'), ('RE_ENROLLED', 'Veterano'), ('CANCELLED', 'Cancelado'), ('SUSPENDED', 'Trancado'), ('TRANSFERRED', 'Transferido'), ('ALUMNI', 'Ex-Aluno'), ('BLOCKED', 'Aluno com Pendências Financeiras'), ('OTHER', 'Outro')], help_text='Status do cliente.', max_length=16, verbose_name='Status do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.classifications')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('promoter_id', models.ForeignKey(help_text='Tutor responsável pelo aluno.', on_delete=django.db.models.deletion.CASCADE, related_name='tutor_responsible', to='profiles.profile', verbose_name='Tutor Responsável')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.IntegerField()),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_payment_counter', models.IntegerField()),
                ('payed_enrollment_fee', models.BooleanField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.landingpage')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.clients')),
            ],
        ),
    ]
