# Generated by Django 4.2.13 on 2024-05-31 14:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_alter_profile_age'),
        ('charges', '0002_charge_enrollment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_base', models.IntegerField(help_text='Ano base para cálculos de mensalidades.', verbose_name='Ano Base')),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('globalsettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finances.globalsettings')),
                ('salario_minimo', models.DecimalField(decimal_places=2, default=Decimal('1412.00'), help_text='Salário mínimo atual.', max_digits=10, verbose_name='Salário Mínimo')),
                ('ipca', models.DecimalField(decimal_places=2, default=Decimal('0.03'), help_text='IPCA acumulado no ano.', max_digits=10, verbose_name='IPCA')),
                ('inpc', models.DecimalField(decimal_places=2, default=Decimal('0.03'), help_text='INPC acumulado no ano.', max_digits=10, verbose_name='INPC')),
                ('igpm', models.DecimalField(decimal_places=2, default=Decimal('0.03'), help_text='IGPM acumulado no ano.', max_digits=10, verbose_name='IGPM')),
                ('selic', models.DecimalField(decimal_places=2, default=Decimal('0.03'), help_text='SELIC acumulado no ano.', max_digits=10, verbose_name='SELIC')),
                ('poupanca', models.DecimalField(decimal_places=2, default=Decimal('0.03'), help_text='Rendimento da poupança acumulado no ano.', max_digits=10, verbose_name='Poupança')),
                ('cdi', models.DecimalField(decimal_places=2, default=Decimal('0.03'), help_text='CDI acumulado no ano.', max_digits=10, verbose_name='CDI')),
                ('dolar', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Cotação do dólar no ano.', max_digits=10, verbose_name='Dólar')),
                ('euro', models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text='Cotação do euro no ano.', max_digits=10, verbose_name='Euro')),
                ('bitcoin', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Cotação do bitcoin no ano.', max_digits=10, verbose_name='Bitcoin')),
                ('bolsa', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Valor do índice da bolsa de valores no ano.', max_digits=10, verbose_name='Bolsa de Valores')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
            bases=('finances.globalsettings',),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('T', 'Taxa de Matrícula'), ('M', 'Mensalidade')], db_column='type', max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pago'), ('A', 'Aguardando Pagamento'), ('C', 'Cancelado')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.charge')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-created_at'],
            },
        ),
    ]
