# Generated by Django 5.0.4 on 2024-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagem carregada', upload_to='images/', verbose_name='Imagem')),
                ('color', models.CharField(help_text='Cor predominante na imagem', max_length=255, verbose_name='Cor')),
                ('description', models.CharField(help_text='Descrição por extenso da imagem', max_length=255, verbose_name='Descrição')),
                ('url', models.CharField(help_text='Link para a imagem', max_length=255, verbose_name='URL')),
                ('width', models.IntegerField(help_text='Largura da imagem', verbose_name='Largura')),
                ('height', models.IntegerField(help_text='Altura da imagem', verbose_name='Altura')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da imagem', verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Background',
                'verbose_name_plural': 'Backgrounds',
            },
        ),
    ]
