# Generated by Django 5.0.4 on 2024-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0002_alter_background_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={},
        ),
        migrations.RemoveField(
            model_name='background',
            name='color',
        ),
        migrations.RemoveField(
            model_name='background',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='background',
            name='description',
        ),
        migrations.RemoveField(
            model_name='background',
            name='height',
        ),
        migrations.RemoveField(
            model_name='background',
            name='image',
        ),
        migrations.RemoveField(
            model_name='background',
            name='width',
        ),
        migrations.AddField(
            model_name='background',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='Backgrounds/'),
        ),
        migrations.AlterField(
            model_name='background',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='background',
            name='url',
            field=models.URLField(),
        ),
    ]
