# Generated by Django 4.2.13 on 2024-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_date', models.DateField()),
                ('status', models.CharField(choices=[('WL', 'Aguardando Liberação'), ('WP', 'Aguardando pagamento'), ('P', 'Pago'), ('AN', 'Análise'), ('BK', 'Bloqueado'), ('CN', 'Cancelado')], default='WP', max_length=2, verbose_name='Status')),
                ('origin', models.CharField(choices=[('MP', 'Mercado Pago'), ('INT', 'Inter Bank')], default='MP', max_length=3, verbose_name='Origin')),
                ('origin_id', models.CharField(verbose_name='Origin Code')),
                ('origin_number', models.CharField(verbose_name='Origin Number')),
                ('bar_code', models.CharField(blank=True, null=True, verbose_name='Bar Code')),
                ('pix_code', models.CharField(blank=True, null=True, verbose_name='Pix Code')),
                ('simple_pix_code', models.CharField(blank=True, null=True, verbose_name='Simple Pix Code')),
                ('txid', models.CharField(blank=True, null=True, verbose_name='Txid')),
            ],
        ),
    ]
