# Generated by Django 5.0.4 on 2024-05-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0002_classifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_date', models.DateField()),
                ('status', models.CharField(choices=[('WL', 'Aguardando Liberação'), ('WP', 'Aguardando pagamento'), ('P', 'Pago'), ('AN', 'Análise'), ('BK', 'Bloqueado'), ('CN', 'Cancelado')], default='WP', max_length=2, verbose_name='Status')),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollments')),
            ],
        ),
    ]
