# Generated by Django 4.2.13 on 2024-05-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='enrollment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollments'),
        ),
    ]
