# Generated by Django 4.2.13 on 2024-05-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='enrollment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollments'),
            preserve_default=False,
        ),
    ]
