# Generated by Django 5.0.6 on 2024-05-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='bar_code',
            field=models.CharField(blank=True, null=True, verbose_name='Bar Code'),
        ),
        migrations.AddField(
            model_name='charge',
            name='origin',
            field=models.CharField(choices=[('MP', 'Mercado Pago'), ('INT', 'Inter Bank')], default='MP', max_length=3, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='charge',
            name='origin_id',
            field=models.CharField(default='928', verbose_name='Origin Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='origin_number',
            field=models.CharField(default='0728', verbose_name='Origin Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='pix_code',
            field=models.CharField(blank=True, null=True, verbose_name='Pix Code'),
        ),
        migrations.AddField(
            model_name='charge',
            name='simple_pix_code',
            field=models.CharField(blank=True, null=True, verbose_name='Simple Pix Code'),
        ),
        migrations.AddField(
            model_name='charge',
            name='txid',
            field=models.CharField(blank=True, null=True, verbose_name='Txid'),
        ),
    ]
