# Generated by Django 5.0.4 on 2024-05-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_cpf_user_first_name_and_more'),
    ]