# Generated by Django 4.2.13 on 2024-05-23 13:02

from django.db import migrations, models
import django.db.models.deletion
import src.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_age'),
        ('users', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', src.users.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='covenant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.CharField(choices=[('PR', 'Promotor'), ('CV', 'Convenio'), ('ST', 'Aluno')], default='ST', max_length=2, verbose_name='user group'),
        ),
    ]
