# Generated by Django 5.0.4 on 2024-05-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='area',
            field=models.CharField(choices=[('adm', 'Administração'), ('cj', 'Ciências Jurídicas'), ('dp', 'Desenvolvimento Pessoal'), ('edu', 'Educação'), ('ead', 'Educação EAD'), ('ea', 'Engenharia e Arquitetura'), ('fv', 'Fotografia e Vídeo'), ('gn', 'Gestão e Negócios'), ('ip', 'Indicação Profissional'), ('mc', 'Marketing e Comunicação'), ('rh', 'Recursos Humanos'), ('sb', 'Saúde e Bem-estar'), ('tec', 'Tecnologia'), ('ti', 'Tecnologia da Informação'), ('pg', 'Formação Pedagógica')], help_text='Área do curso', max_length=3, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('12', '2 Semestres'), ('18', '3 Semestres'), ('24', '4 Semestres'), ('30', '5 Semestres'), ('36', '6 Semestres'), ('42', '7 Semestres'), ('48', '8 Semestres'), ('54', '9 Semestres'), ('60', '10 Semestres')], help_text='Duração do curso', max_length=2, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('tec', 'Tecnólogo'), ('r2', 'Licenciatura R2'), ('bch', 'Bacharelado'), ('lic', 'Licenciatura'), ('pg', 'Formação Pedagógica')], help_text='Tipo do curso', max_length=3, verbose_name='Tipo'),
        ),
    ]
