# Generated by Django 4.2.13 on 2024-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('api_version', models.CharField(max_length=10)),
                ('request_id', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
                ('payment_id', models.CharField(max_length=50)),
                ('live_mode', models.BooleanField()),
                ('type', models.CharField(max_length=50)),
                ('user_id', models.BigIntegerField()),
            ],
        ),
    ]
