# Generated by Django 4.2.13 on 2024-06-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_promotional_code'),
        ('mercado_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Token de Acesso.', max_length=300, verbose_name='Token de Acesso')),
                ('public_key', models.CharField(help_text='Chave mp', max_length=300, verbose_name='Chave mp')),
                ('refresh_token', models.CharField(max_length=300, verbose_name='Refresh_token')),
                ('user_id', models.CharField(help_text='MP user_id', max_length=300)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
