# Generated by Django 5.0.4 on 2024-04-17 11:53

import modules.core.profiles.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome completo.", max_length=100, verbose_name="Nome"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        help_text="Data de Nascimento",
                        validators=[
                            modules.core.profiles.validators.validate_birthdate
                        ],
                        verbose_name="Data de Nascimento",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="CPF no formato 'xxx.xxx.xxx-xx'",
                        max_length=14,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Número de celular com Whatsapp",
                        max_length=11,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        help_text="Gênero",
                        max_length=1,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("S", "Solteiro(a)"),
                            ("C", "Casado(a)"),
                            ("D", "Divorciado(a)"),
                            ("V", "Viúvo(a)"),
                        ],
                        help_text="Estado civil",
                        max_length=1,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "academic_status",
                    models.CharField(
                        choices=[
                            ("F", "Ensino Fundamental"),
                            ("M", "Ensino Médio"),
                            ("G", "Ensino Superior - Graduação"),
                            ("P", "Ensino Superior - Pós-Graduação"),
                        ],
                        help_text="Escolaridade",
                        max_length=1,
                        verbose_name="Escolaridade",
                    ),
                ),
                (
                    "academic_status_conclusion",
                    models.BooleanField(
                        default=False,
                        help_text="Concluido",
                        verbose_name="Escolaridade",
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        help_text="Nome completo da mãe.",
                        max_length=100,
                        verbose_name="Nome da Mãe",
                    ),
                ),
                (
                    "birth_state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        help_text="Estado de nascimento.",
                        max_length=2,
                        verbose_name="Estado de Nascimento",
                    ),
                ),
                (
                    "birth_city",
                    models.CharField(
                        help_text="Cidade de nascimento.",
                        max_length=100,
                        verbose_name="Cidade de Nascimento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Perfis",
            },
        ),
        migrations.CreateModel(
            name="PostGraduation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Cidade")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        choices=[
                            ("C", "Cursando"),
                            ("F", "Concluído"),
                            ("X", "Cancelado"),
                            ("T", "Trancado"),
                        ],
                        max_length=1,
                        verbose_name="Situação",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=255, verbose_name="Nome do Curso"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "postgraduation_type",
                    models.CharField(
                        choices=[
                            ("D", "Doutorado"),
                            ("M", "Mestrado"),
                            ("P", "Pós-Doutorado"),
                        ],
                        max_length=33,
                        verbose_name="Tipo de Pós-Graduação",
                    ),
                ),
                (
                    "certificate",
                    models.FileField(upload_to="certificates/", verbose_name="Diploma"),
                ),
                (
                    "history",
                    models.FileField(upload_to="histories/", verbose_name="Histórico"),
                ),
                (
                    "curriculum",
                    models.FileField(upload_to="curriculums/", verbose_name="Ementa"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                        verbose_name="Perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pós-Graduação",
                "verbose_name_plural": "Pós-Graduações",
            },
        ),
        migrations.CreateModel(
            name="HighSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Cidade")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        choices=[
                            ("C", "Cursando"),
                            ("F", "Concluído"),
                            ("X", "Cancelado"),
                            ("T", "Trancado"),
                        ],
                        max_length=33,
                        verbose_name="Situação",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        upload_to="certificates/", verbose_name="Certificado"
                    ),
                ),
                (
                    "history",
                    models.FileField(upload_to="histories/", verbose_name="Histórico"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="high_school",
                        to="profiles.profile",
                        verbose_name="Perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ensino Médio",
                "verbose_name_plural": "Ensino Médio",
            },
        ),
        migrations.CreateModel(
            name="Graduation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Cidade")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        choices=[
                            ("C", "Cursando"),
                            ("F", "Concluído"),
                            ("X", "Cancelado"),
                            ("T", "Trancado"),
                        ],
                        max_length=1,
                        verbose_name="Situação",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data de Início")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=255, verbose_name="Nome do Curso"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "graduation_type",
                    models.CharField(
                        choices=[
                            ("B", "Bacharelado"),
                            ("L", "Licenciatura"),
                            ("T", "Tecnólogo"),
                        ],
                        max_length=1,
                        verbose_name="Tipo de Graduação",
                    ),
                ),
                (
                    "certificate",
                    models.FileField(upload_to="certificates/", verbose_name="Diploma"),
                ),
                (
                    "history",
                    models.FileField(upload_to="histories/", verbose_name="Histórico"),
                ),
                ("duration", models.CharField(max_length=255, verbose_name="Duração")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                        verbose_name="Perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Graduação",
                "verbose_name_plural": "Graduações",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Cidade")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        help_text="Código Postal.", max_length=9, verbose_name="CEP"
                    ),
                ),
                ("street", models.CharField(max_length=255, verbose_name="Rua")),
                ("number", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Complemento"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(max_length=255, verbose_name="Bairro"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="profiles.profile",
                        verbose_name="Perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
    ]
