# Generated by Django 5.0.4 on 2024-05-01 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='regiao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='graduation',
            options={'verbose_name': 'Informação sobre a graduação', 'verbose_name_plural': 'Informações sobre as graduações'},
        ),
        migrations.AlterModelOptions(
            name='highschool',
            options={'verbose_name': 'Ensino Médio', 'verbose_name_plural': 'Informações sobre Ensino Médio'},
        ),
        migrations.AlterModelOptions(
            name='postgraduation',
            options={'verbose_name': 'Informação sobre a pós-graduação', 'verbose_name_plural': 'Informações sobre as pós-graduações'},
        ),
        migrations.RemoveField(
            model_name='postgraduation',
            name='history',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('cpf', 'birth_date')},
        ),
        migrations.AddField(
            model_name='postgraduation',
            name='duration',
            field=models.CharField(default=0, help_text='Tempo de duração do curso.', max_length=255, verbose_name='Duração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_bool',
            field=models.BooleanField(default=False, editable=False, help_text='Endereço cadastrado.', verbose_name='Endereço Cadastrado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Idade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='educational_bool',
            field=models.BooleanField(default=False, editable=False, help_text='Escolaridade cadastrada.', verbose_name='Escolaridade Cadastrada'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bool',
            field=models.BooleanField(default=False, editable=False, help_text='Perfil cadastrado.', verbose_name='Perfil Cadastrado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Escolha a cidade.', max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Escolha o estado.', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='certificate',
            field=models.FileField(help_text='Diploma de conclusão da graduação.', upload_to='certificates/', verbose_name='Diploma'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='city',
            field=models.CharField(help_text='Escolha a cidade.', max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='duration',
            field=models.CharField(help_text='Tempo de duração do curso.', max_length=255, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='graduation_type',
            field=models.CharField(choices=[('B', 'Bacharelado'), ('L', 'Licenciatura'), ('T', 'Tecnólogo')], help_text='Tipo de graduação.', max_length=1, verbose_name='Tipo de Graduação'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='history',
            field=models.FileField(help_text='Histórico e Ementa da graduação cursada.', upload_to='histories/', verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='institution_name',
            field=models.CharField(help_text='Nome da instituição de ensino.', max_length=255, verbose_name='Nome da Instituição'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation', related_query_name='graduation', to='profiles.profile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='situation',
            field=models.CharField(choices=[('C', 'Cursando'), ('F', 'Concluído'), ('X', 'Cancelado'), ('T', 'Trancado')], help_text='Situação atual do curso.', max_length=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Escolha o estado.', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='certificate',
            field=models.FileField(help_text='Certificado de conclusão do ensino médio.', upload_to='certificates/', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='city',
            field=models.CharField(help_text='Escolha a cidade.', max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='history',
            field=models.FileField(help_text='Histórico escolar do ensino médio.', upload_to='histories/', verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='high_school', related_query_name='high_school', to='profiles.profile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='situation',
            field=models.CharField(choices=[('C', 'Cursando'), ('F', 'Concluído'), ('X', 'Cancelado'), ('T', 'Trancado')], help_text='Atual situação do ensino médio.', max_length=33, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Escolha o estado.', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='certificate',
            field=models.FileField(help_text='Diploma de conclusão da pós-graduação.', upload_to='certificates/', verbose_name='Diploma'),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='city',
            field=models.CharField(help_text='Escolha a cidade.', max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='curriculum',
            field=models.FileField(help_text='Ementa da pós-graduação cursada.', upload_to='curriculums/', verbose_name='Ementa'),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='institution_name',
            field=models.CharField(help_text='Nome da instituição de ensino.', max_length=255, verbose_name='Nome da Instituição'),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='postgraduation_type',
            field=models.CharField(choices=[('D', 'Doutorado'), ('M', 'Mestrado'), ('P', 'Pós-Doutorado')], help_text='Tipo de pós-graduação.', max_length=1, verbose_name='Tipo de Pós-Graduação'),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postgraduation', related_query_name='postgraduation', to='profiles.profile', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='situation',
            field=models.CharField(choices=[('C', 'Cursando'), ('F', 'Concluído'), ('X', 'Cancelado'), ('T', 'Trancado')], help_text='Situação atual do curso.', max_length=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='postgraduation',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Escolha o estado.', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(help_text='CPF no formato "somente números".', max_length=14, unique=True, verbose_name='CPF - Cadastro de Pessoa Física'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], help_text='Gênero', max_length=1, verbose_name='Gênero (Sexo)'),
        ),
        migrations.CreateModel(
            name='ContractsEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_user_promoter', models.FileField(editable=False, help_text='Contrato do promotor.', upload_to='contracts/', verbose_name='Contrato do Promotor')),
                ('contract_user_promoter_sign_bool', models.BooleanField(default=False, editable=False, help_text='Contrato assinado.', verbose_name='Contrato Assinado')),
                ('contract_user_agreement', models.FileField(editable=False, help_text='Contrato do convênio.', upload_to='contracts/', verbose_name='Contrato do Convênio')),
                ('contract_user_agreement_sign_bool', models.BooleanField(default=False, editable=False, help_text='Contrato assinado.', verbose_name='Contrato Assinado')),
                ('promoter_contract_signing_photo', models.ImageField(editable=False, help_text='Foto/Assinatura do contrato.', upload_to='photos/', verbose_name='Foto/Assinatura do contrato de promotor')),
                ('agreement_contract_signing_photo', models.ImageField(editable=False, help_text='Foto/Assinatura do contrato.', upload_to='photos/', verbose_name='Foto/Assinatura do contrrato de convênio')),
                ('contract_client_enrollment', models.FileField(editable=False, help_text='Contrato de matrícula.', upload_to='contracts/', verbose_name='Contrato da Matrícula')),
                ('enrollment_contract_signing_photo', models.ImageField(editable=False, help_text='Foto/Assinatura do contrato de matrícula.', upload_to='photos/', verbose_name='Foto/Assinatura do Contrato de Matrícula.')),
                ('enrollment_contract_sign_bool', models.BooleanField(default=False, editable=False, help_text='Contrato assinado.', verbose_name='Contrato Assinado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Contrato de Matrícula',
                'verbose_name_plural': 'Contratos de Matrícula',
            },
        ),
        migrations.CreateModel(
            name='mesorregiao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('UF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.estado')),
            ],
        ),
        migrations.CreateModel(
            name='microrregiao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('mesorregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.mesorregiao')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.regiao'),
        ),
        migrations.CreateModel(
            name='regiao_intermediaria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('UF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.estado')),
            ],
        ),
        migrations.CreateModel(
            name='regiao_imediata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('regiao_intermediaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.regiao_intermediaria')),
            ],
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('UF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.estado')),
                ('microrregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.microrregiao')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.regiao')),
                ('regiao_imediata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.regiao_imediata')),
                ('regiao_intermediaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.regiao_intermediaria')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='academic_status_conclusion',
        ),
    ]
