# Generated by Django 5.0.4 on 2024-05-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_estado_regiao_alter_graduation_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regiao_imediata',
            new_name='RegiaoImediata',
        ),
        migrations.RenameModel(
            old_name='regiao_intermediaria',
            new_name='RegiaoIntermediaria',
        ),
    ]
