# Generated by Django 4.2.13 on 2024-06-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promotional_code',
            field=models.CharField(default='test', max_length=16, verbose_name='Código Promocional'),
            preserve_default=False,
        ),
    ]
