# Generated by Django 4.2.13 on 2024-05-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da página de destino.', max_length=200, verbose_name='Nome')),
                ('campaign_start', models.DateField(help_text='Data de início da campanha.', verbose_name='Início da Campanha')),
                ('campaign_end', models.DateField(help_text='Data de término da campanha.', verbose_name='Fim da Campanha')),
                ('active', models.BooleanField(default=True, help_text='Indica se a campanha está ativa.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Página de Destino',
                'verbose_name_plural': 'Páginas de Destino',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título da seção. Opcional.', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo da seção. Opcional.', max_length=200, verbose_name='Subtítulo')),
                ('text', models.TextField(blank=True, help_text='Texto principal da seção. Opcional.', verbose_name='Texto')),
                ('image', models.FileField(blank=True, help_text='Imagem da seção. Suporta PNG/SVG. Opcional.', null=True, upload_to='images/', verbose_name='Imagem')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Campo JSON para dados adicionais. Flexível e opcional.', verbose_name='Informações Adicionais')),
                ('landing_page_id', models.ForeignKey(help_text='Página de destino à qual a seção pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='campaigns.landingpage', verbose_name='Página de Destino')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
            },
        ),
        migrations.CreateModel(
            name='ValueProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Ícone relacionado à proposta de valor. Opcional.', max_length=200, verbose_name='Ícone')),
                ('title', models.CharField(help_text='Título da proposta de valor.', max_length=200, verbose_name='Título')),
                ('text', models.TextField(help_text='Descrição da proposta de valor.', verbose_name='Texto')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor numérico da proposta.', max_digits=10, verbose_name='Valor')),
                ('frequency', models.CharField(help_text="Frequência de aplicação do valor, como 'Mensal', 'Anual', 'Única'.", max_length=50, verbose_name='Frequência')),
                ('landing_page_id', models.ForeignKey(help_text='Página de destino à qual a proposta de valor pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='value_propositions', to='campaigns.landingpage', verbose_name='Página de Destino')),
            ],
            options={
                'verbose_name': 'Proposta de Valor',
                'verbose_name_plural': 'Propostas de Valor',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Texto do depoimento.', verbose_name='Texto')),
                ('author_name', models.CharField(help_text='Nome do autor do depoimento.', max_length=200, verbose_name='Nome do Autor')),
                ('author_title', models.CharField(blank=True, help_text='Título profissional do autor do depoimento. Opcional.', max_length=200, verbose_name='Título do Autor')),
                ('author_photo', models.ImageField(blank=True, help_text='Foto do autor do depoimento. Opcional.', null=True, upload_to='testimonials/', verbose_name='Foto do Autor')),
                ('landing_page_id', models.ForeignKey(help_text='Página de destino à qual o depoimento pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='campaigns.landingpage', verbose_name='Página de Destino')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da estatística.', max_length=200, verbose_name='Título')),
                ('value', models.CharField(help_text='Valor da estatística.', max_length=200, verbose_name='Valor')),
                ('icon', models.CharField(blank=True, help_text='URL ou caminho para o ícone SVG. Opcional.', max_length=200, verbose_name='Ícone')),
                ('section', models.ForeignKey(help_text='Seção à qual a estatística pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='campaigns.section', verbose_name='Seção')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('landing_page_id', models.ForeignKey(help_text='Deixe em branco para perguntas gerais, ou escolha uma página de destino específica para perguntas específicas.', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='campaigns.landingpage', verbose_name='Página de Destino')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='URL ou caminho para o ícone SVG. Opcional.', max_length=200, verbose_name='Ícone')),
                ('title', models.CharField(help_text='Título do cartão.', max_length=200, verbose_name='Título')),
                ('text', models.TextField(help_text='Texto principal do cartão.', verbose_name='Texto')),
                ('section', models.ForeignKey(help_text='Seção à qual o cartão pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='campaigns.section', verbose_name='Seção')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
