# Generated by Django 5.0.4 on 2024-05-01 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('courses', '0002_alter_course_area_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_base', models.IntegerField(help_text='Ano base para cálculos de mensalidades.', verbose_name='Ano Base')),
            ],
        ),
        migrations.RenameField(
            model_name='section',
            old_name='landing_page',
            new_name='LandingPageID',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='landing_page',
            new_name='LandingPageID',
        ),
        migrations.RenameField(
            model_name='valueproposition',
            old_name='landing_page',
            new_name='LandingPageID',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='landing_page',
        ),
        migrations.AddField(
            model_name='faq',
            name='LandingPageID',
            field=models.ForeignKey(default=1, help_text='Deixe em branco para perguntas gerais, ou escolha uma página de destino específica para perguntas específicas.', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='campaigns.landingpage', verbose_name='Página de Destino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.FileField(blank=True, help_text='Imagem da seção. Suporta PNG/SVG. Opcional.', null=True, upload_to='images/', verbose_name='Imagem'),
        ),
        migrations.CreateModel(
            name='Classifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classification', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
            },
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('globalsettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.globalsettings')),
                ('salario_minimo', models.DecimalField(decimal_places=2, default=1412.0, help_text='Salário mínimo atual.', max_digits=10, verbose_name='Salário Mínimo')),
                ('ipca', models.DecimalField(decimal_places=2, default=0.03, help_text='IPCA acumulado no ano.', max_digits=10, verbose_name='IPCA')),
                ('inpc', models.DecimalField(decimal_places=2, default=0.03, help_text='INPC acumulado no ano.', max_digits=10, verbose_name='INPC')),
                ('igpm', models.DecimalField(decimal_places=2, default=0.03, help_text='IGPM acumulado no ano.', max_digits=10, verbose_name='IGPM')),
                ('selic', models.DecimalField(decimal_places=2, default=0.03, help_text='SELIC acumulado no ano.', max_digits=10, verbose_name='SELIC')),
                ('poupanca', models.DecimalField(decimal_places=2, default=0.03, help_text='Rendimento da poupança acumulado no ano.', max_digits=10, verbose_name='Poupança')),
                ('cdi', models.DecimalField(decimal_places=2, default=0.03, help_text='CDI acumulado no ano.', max_digits=10, verbose_name='CDI')),
                ('dolar', models.DecimalField(decimal_places=2, default=5.0, help_text='Cotação do dólar no ano.', max_digits=10, verbose_name='Dólar')),
                ('euro', models.DecimalField(decimal_places=2, default=6.0, help_text='Cotação do euro no ano.', max_digits=10, verbose_name='Euro')),
                ('bitcoin', models.DecimalField(decimal_places=2, default=50000.0, help_text='Cotação do bitcoin no ano.', max_digits=10, verbose_name='Bitcoin')),
                ('bolsa', models.DecimalField(decimal_places=2, default=100000.0, help_text='Valor do índice da bolsa de valores no ano.', max_digits=10, verbose_name='Bolsa de Valores')),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
            bases=('campaigns.globalsettings',),
        ),
    ]
