# Generated by Django 5.0.4 on 2024-05-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_globalsettings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='LandingPageID',
            new_name='landing_page_id',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='LandingPageID',
            new_name='landing_page_id',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='LandingPageID',
            new_name='landing_page_id',
        ),
        migrations.RenameField(
            model_name='valueproposition',
            old_name='LandingPageID',
            new_name='landing_page_id',
        ),
    ]
